package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommonArea<M extends BaseCommonArea<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 省市区名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 省市区名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 省市编码
	 */
	public void setPid(java.lang.Long pid) {
		set("pid", pid);
	}
	
	/**
	 * 省市编码
	 */
	public java.lang.Long getPid() {
		return getLong("pid");
	}

	/**
	 * 排序代码
	 */
	public void setDisorder(java.lang.Integer disorder) {
		set("disorder", disorder);
	}
	
	/**
	 * 排序代码
	 */
	public java.lang.Integer getDisorder() {
		return getInt("disorder");
	}

	/**
	 * 省区域代码
	 */
	public void setProcode(java.lang.String procode) {
		set("procode", procode);
	}
	
	/**
	 * 省区域代码
	 */
	public java.lang.String getProcode() {
		return getStr("procode");
	}

}
