package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 用户名
	 */
	public void setLoginName(java.lang.String loginName) {
		set("loginName", loginName);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getLoginName() {
		return getStr("loginName");
	}

	/**
	 * 密码
	 */
	public void setPassword(byte[] password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public byte[] getPassword() {
		return get("password");
	}

	/**
	 * 状态1启用/0禁用/2删除
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 状态1启用/0禁用/2删除
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 电话号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 电话号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	/**
	 * 角色ID
	 */
	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}
	
	/**
	 * 角色ID
	 */
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
