package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccessToken<M extends BaseAccessToken<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 微信APPID
	 */
	public void setAppId(java.lang.String appId) {
		set("appId", appId);
	}
	
	/**
	 * 微信APPID
	 */
	public java.lang.String getAppId() {
		return getStr("appId");
	}

	/**
	 * 开发者秘钥
	 */
	public void setAppsecret(java.lang.String appsecret) {
		set("appsecret", appsecret);
	}
	
	/**
	 * 开发者秘钥
	 */
	public java.lang.String getAppsecret() {
		return getStr("appsecret");
	}

	/**
	 * 更新时间
	 */
	public void setUpdated(java.lang.Long updated) {
		set("updated", updated);
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.Long getUpdated() {
		return getLong("updated");
	}

}
