package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommonFunctionOperation<M extends BaseCommonFunctionOperation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 操作名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 操作名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 按键值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 按键值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 按键链接
	 */
	public void setLink(java.lang.String link) {
		set("link", link);
	}
	
	/**
	 * 按键链接
	 */
	public java.lang.String getLink() {
		return getStr("link");
	}

	/**
	 * 按键图标值
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 按键图标值
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 所属功能id
	 */
	public void setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
	}
	
	/**
	 * 所属功能id
	 */
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	/**
	 * 按钮样式
	 */
	public void setStyle(java.lang.String style) {
		set("style", style);
	}
	
	/**
	 * 按钮样式
	 */
	public java.lang.String getStyle() {
		return getStr("style");
	}

	/**
	 * 有效性
	 */
	public void setValid(java.lang.Integer valid) {
		set("valid", valid);
	}
	
	/**
	 * 有效性
	 */
	public java.lang.Integer getValid() {
		return getInt("valid");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	/**
	 * 按键类型
	 */
	public void setButtonType(java.lang.String buttonType) {
		set("buttonType", buttonType);
	}
	
	/**
	 * 按键类型
	 */
	public java.lang.String getButtonType() {
		return getStr("buttonType");
	}

}
