package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommonRoleList<M extends BaseCommonRoleList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 角色名称
	 */
	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}
	
	/**
	 * 角色名称
	 */
	public java.lang.String getRoleName() {
		return getStr("roleName");
	}

	/**
	 * 角色级别
	 */
	public void setRoleLevel(java.lang.Integer roleLevel) {
		set("roleLevel", roleLevel);
	}
	
	/**
	 * 角色级别
	 */
	public java.lang.Integer getRoleLevel() {
		return getInt("roleLevel");
	}

	/**
	 * 有效性
	 */
	public void setValid(java.lang.Integer valid) {
		set("valid", valid);
	}
	
	/**
	 * 有效性
	 */
	public java.lang.Integer getValid() {
		return getInt("valid");
	}

}
