package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRsaKeyPair<M extends BaseRsaKeyPair<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 商户Id
	 */
	public void setMerchantId(java.lang.Integer merchantId) {
		set("merchantId", merchantId);
	}
	
	/**
	 * 商户Id
	 */
	public java.lang.Integer getMerchantId() {
		return getInt("merchantId");
	}

	/**
	 * 后台用户Id
	 */
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	/**
	 * 后台用户Id
	 */
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	/**
	 * 私钥
	 */
	public void setPrivateKey(java.lang.String privateKey) {
		set("privateKey", privateKey);
	}
	
	/**
	 * 私钥
	 */
	public java.lang.String getPrivateKey() {
		return getStr("privateKey");
	}

	/**
	 * 公钥
	 */
	public void setPublicKey(java.lang.String publicKey) {
		set("publicKey", publicKey);
	}
	
	/**
	 * 公钥
	 */
	public java.lang.String getPublicKey() {
		return getStr("publicKey");
	}

}
