package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleMenuPermission<M extends BaseRoleMenuPermission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public void setMenuId(java.lang.Integer menuId) {
		set("menuId", menuId);
	}
	
	public java.lang.Integer getMenuId() {
		return getInt("menuId");
	}

	public void setValid(java.lang.Integer valid) {
		set("valid", valid);
	}
	
	public java.lang.Integer getValid() {
		return getInt("valid");
	}

}
