package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("access_token", "id", AccessToken.class);
		arp.addMapping("bank_info", "id", BankInfo.class);
		arp.addMapping("common_area", "id", CommonArea.class);
		arp.addMapping("common_constant", "id", CommonConstant.class);
		arp.addMapping("common_function_menu", "id", CommonFunctionMenu.class);
		arp.addMapping("common_function_operation", "id", CommonFunctionOperation.class);
		arp.addMapping("common_platform_param", "id", CommonPlatformParam.class);
		arp.addMapping("common_role_list", "id", CommonRoleList.class);
		arp.addMapping("common_system_log", "id", CommonSystemLog.class);
		arp.addMapping("google", "id", Google.class);
		arp.addMapping("role_menu_permission", "id", RoleMenuPermission.class);
		arp.addMapping("role_operation_permission", "id", RoleOperationPermission.class);
		arp.addMapping("rsa_key_pair", "id", RsaKeyPair.class);
		arp.addMapping("user", "id", User.class);
	}
}

