package com.demo.common.model;

import com.demo.common.model.base.BaseAccessToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccessToken extends BaseAccessToken<AccessToken> {
	
}
