package com.demo.common.model;

import com.demo.common.model.base.BaseBankInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankInfo extends BaseBankInfo<BankInfo> {
	
}
