package com.demo.common.model;

import com.demo.common.model.base.BaseCommonArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonArea extends BaseCommonArea<CommonArea> {
	
}
