package com.demo.common.model;

import com.demo.common.model.base.BaseCommonFunctionMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonFunctionMenu extends BaseCommonFunctionMenu<CommonFunctionMenu> {
	
}
