package com.demo.common.model;

import com.demo.common.model.base.BaseCommonConstant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonConstant extends BaseCommonConstant<CommonConstant> {
	
}
