package com.demo.common.model;

import com.demo.common.model.base.BaseCommonPlatformParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonPlatformParam extends BaseCommonPlatformParam<CommonPlatformParam> {
	
}
