package com.demo.common.model;

import com.demo.common.model.base.BaseCommonSystemLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonSystemLog extends BaseCommonSystemLog<CommonSystemLog> {
	
}
