package com.demo.common.model;

import com.demo.common.model.base.BaseCommonRoleList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonRoleList extends BaseCommonRoleList<CommonRoleList> {
	
}
