package com.demo.common.model;

import com.demo.common.model.base.BaseCommonFunctionOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonFunctionOperation extends BaseCommonFunctionOperation<CommonFunctionOperation> {
	
}
