package com.demo.common.model;

import com.demo.common.model.base.BaseRoleOperationPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleOperationPermission extends BaseRoleOperationPermission<RoleOperationPermission> {
	
}
