package com.demo.common.model;

import com.demo.common.model.base.BaseRoleMenuPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenuPermission extends BaseRoleMenuPermission<RoleMenuPermission> {
	
}
