package com.demo.common.model;

import com.demo.common.model.base.BaseRsaKeyPair;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RsaKeyPair extends BaseRsaKeyPair<RsaKeyPair> {
	
}
